### ISSUE TITLE
Remove Button Functionality

### ISSUE THREAD

**Issue by kylem038** [kylem038/linked-list#3]
When the user clicks on the “Remove” button, the link should be removed from the page

**Comment by blakeworsley** [comment]
I did this as well because it was an extra line of code. I will show you tomorrow but it got a bit confusing.. you can call me if you want me to walk you through it. 970-819-0860.

**Comment by kylem038** [comment]
Sounds good - I've got it where all the bookmarks are removed when you click the button. working on getting only the one you click to get removed.
